# Sample by https://github.com/compose-spec/compose-spec/blob/master/spec.md

services:
  main:
    build: ./main-service
    ports:
      - "3333:3333"
    networks:
      front-tier: {}
      back-tier:
        ipv4_address: 172.20.0.2
    container_name: main-service
    restart: always
    command: node index.js

  logger:
    build: ./logger-service
    ports:
      - "3332"
    networks:
      - back-tier
    container_name: logger-service
    restart: always
    command: node index.js
    depends_on:
      - "main"
  
  users:
    build: ./authentication-service
    ports:
      - "3330"
    networks:
      - back-tier
    container_name: authentication-service
    restart: always
    command: node index.js
    depends_on:
      - "main"

  static-file:
    build: ./static-file-service
    ports:
      - "3331"
    networks:
      - back-tier
    container_name: static-file-service
    restart: always
    command: node index.js
    depends_on:
      - "main"

networks:
  front-tier: 
    name: frontend-network
    driver: bridge
     
  back-tier:
    name: backend-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16